### ISSUE TITLE
Downloads sometimes getting stuck before completion?

### ISSUE THREAD

**Issue by RickyRomero** [xcodereleases/xcinfo#11]
Encountered this issue a couple of times with xcinfo after installing from source 4 days ago. My download for Xcode 12.3 got stuck at 99.6% completion. I tried downloading other Xcode releases a couple of days ago and the downloads got stuck as well, at lower percentages. This is on an Ethernet connection which should be otherwise rock-solid.

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/233891/102170501-656b5600-3e49-11eb-96ab-e763217fb803.png">

xcinfo is at 0% CPU in Activity Monitor with no child processes. Spindump doesn't show any clues either:
[Sample of xcinfo.txt](https://github.com/xcodereleases/xcinfo/files/5693306/Sample.of.xcinfo.txt)

---

As I was writing this, I tried again with the `--verbose` flag. This time it installed Xcode successfully for the first time, but didn't yield any more clues. Hesitant to run more tests as I'm at home on a metered Internet connection.

Aside from these issues, I like this utility a lot! It takes care of lots of really tedious steps. It seems to do a good job of automating installation of new Xcode releases (when the download works). It also makes it a lot easier to grab a specific Xcode version, or check which versions you have installed. It's really nice that it speeds up signing into the Apple Developer Portal. I like that the xip extraction gives you fine-grained progress updates so you can see it moving along.

**Comment by trispo** [comment]
I did encounter the same issue the other day but I do not have an answer on why this happens. When testing the download with Xcode it always completes.
