### ISSUE TITLE
Is renaming Xcode with a space problematic?

### ISSUE THREAD

**Issue by RickyRomero** [xcodereleases/xcinfo#12]
When xcinfo installs Xcode, it renames it with the version number, like so: `/Applications/Xcode 12.3.app`

This may be problematic for certain development setups. For example, Homebrew complains when the selected Xcode's name has a space in it if you run `brew doctor`:

```
Warning: Your Xcode is configured with an invalid path.
You should change it to the correct path:
  sudo xcode-select -switch /Applications/Xcode.app
```

Not sure if that's prone to breaking Homebrew's formulae during builds, but it seems plausible...

**Comment by trispo** [comment]
I did think of changing this behavior myself the other day. A dependency of Fastlane also requires that there is at least one Xcode called Xcode.app. So I thought to change the renaming behavior to call the just downloaded version to Xcode.app and rename an potentially existing Xcode.app version to to a an app with its version in the name separated with dashes. 

Would you like to create a Pull Request for this @RickyRomero?
