### ISSUE TITLE
CMake get confused about the paths with spaces

### ISSUE THREAD

**Issue by NoWiseMan** [xcodereleases/xcinfo#17]
I get errors from CMake that it can't find the current installed compiler.

Changeing the path from "Xcode 12.5 RC 1" to "Xcode_12.5_RC_1" fix the issues.
Looks like some tools out there still don't like spaces in the path

**Comment by trispo** [comment]
This is a duplicate of #12 and already fixed for version 0.6.1 which will be released soon.

**Comment by ricobeck** [comment]
Resolved in 0.7.0

@NoWiseMan please check and close this issue if it's working.

**Comment by NoWiseMan** [comment]
works
great job
