### ISSUE TITLE
After install finished, xip still in temp directory

### ISSUE THREAD

**Issue by cntrump** [xcodereleases/xcinfo#19]
`/private/var/folders/hj/sbcd73xn1rv0f86qgyptbk2h0000gn/T/Xcode_12.5_Release_Candidate.xip ` is not deleted or moved to  current directory

**Comment by cntrump** [comment]
And why rename my default `Xcode.app` to `Xcode 12.4.app` ...

**Comment by trispo** [comment]
> `/private/var/folders/hj/sbcd73xn1rv0f86qgyptbk2h0000gn/T/Xcode_12.5_Release_Candidate.xip ` is not deleted or moved to current directory
Thanks for this advice. The downloaded XIP will be deleted after extraction from the next version on. This behavior can be disabled with the `--disable-xip-deletion`flag.

**Comment by trispo** [comment]
> And why rename my default Xcode.app to Xcode 12.4.app ...

There was the decision to create a symlink from the newly installed Xcode to Xcode.app by default. You can disable this with the CLI flag `--no-symlink`.
