### ISSUE TITLE
At 100% of the download, `remaining` and `speed` stay at the last values.

### ISSUE THREAD

**Issue by trispo** [xcodereleases/xcinfo#2]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/1045441/66070383-7cc66800-e551-11e9-8703-fc83bad73791.png">

**Comment by ricobeck** [comment]
Should be something like
‘Download completed in 32 minutes’

**Comment by trispo** [comment]
Really? Is this valuable information?
