### ISSUE TITLE
Installation failure "application could not be moved" and cache reset

### ISSUE THREAD

**Issue by finestructure** [xcodereleases/xcinfo#24]
I'm on a slow connection and I love that xcinfo is dealing with all the little request timeouts I usually get on that long download. However, I've been getting a weird error a few times after download and on install that resets the cache and makes the download restart when I re-issue the command:

<img width="795" alt="CleanShot_2021-10-20_at_10 51 152x" src="https://user-images.githubusercontent.com/65520/138061930-c6e0c1d5-fc60-4527-bf75-91a25856f105.png">

I suspect the "move" error is due to an `Xcode.app` alias I've set pointing at Xcode_13.0. I'm retrying after removing that alias but it'd be great if xcinfo could give more details here and didn't wipe the download when it encounters that error.

I'm now using `xcinfo download` instead of `install` to see if that'll give me multiple shots - or leave me with an xip that I can install manually.

I'll poke around the source a bit if I can figure something out but any help/pointers greatly appreciated!

xcinfo is making Xcode installs so much nicer :)

**Comment by funkenstrahlen** [comment]
I see the exact same error message after upgrading to Monterey.

**Comment by trispo** [comment]
I got this error message, too. My understanding was, that my disk space was not sufficient enough. But in your cases the unxip did happen already. Well, we definitely need to add better error messages if possible to further investigate.

**Comment by funkenstrahlen** [comment]
I also think it has something to do with the available disk space. Because I downloaded the XIP manually and tried to extract it. Then I also received the error message that there is enough disk space. When I tried to extract again manually it worked.

**Comment by VilemKurz** [comment]
Same problem here. Big Sur 11.6.2, 170 gb available

**Comment by trispo** [comment]
xcinfo 1.0.3 should fix this issue. If prints the correct error to the stdout.
