### ISSUE TITLE
print xip file temporary location

### ISSUE THREAD

**Issue by arielelkin** [xcodereleases/xcinfo#27]
Feature request: when downloading+installing a new Xcode version, print the download's temporary location. 

Many times we get a `"application could not be moved into /Applications"` error because of a lack of disk space. In those cases the installation fails, and we need to manually free up disk space. After which we have to download Xcode again if we were to install via xcinfo. So it would be useful if xcinfo printed the location of the downloaded xip so we can proceed with the install manually. 

Related to https://github.com/xcodereleases/xcinfo/issues/24

**Comment by trispo** [comment]
In the mean time you can open the temporary folder with the following command:

open $TMPDIR

This folder should contain the downloaded Xcode.xip file.

**Comment by trispo** [comment]
xcinfo 1.0.3 is now available which saves the file in your Downloads directory and also prints the path to the stdout.
