### ISSUE TITLE
[Feature] Optionally preserve xip file + optionally input xip path to xcinfo

### ISSUE THREAD

**Issue by gobetti** [xcodereleases/xcinfo#28]
hi all!

xcinfo has been helping me speed up the process of updating Xcode on a machine, however if I need to do it on multiple then each has to go through the download process again. When I did it manually, I used to download the xip file once and then share it with the other machines.

I guess it might not be hard to achieve the same with xcinfo, as long as we can choose to preserve the xip file, so we can copy it to the other machines and then input its path to xcinfo. If that already exists please let me know, I'm assuming it doesn't based on the readme only.

example on machine 1:
```
xcinfo install 13.3.1 --preserve-xip
```
(manually copy xip from machine 1 to 2)
example on machine 2+:
```
xcinfo install 13.3.1 --xip-path ~/Downloads/Xcode_13.3.1.xip
```
I haven't put much thought into whether we need to specify the version when we're already inputting a xip, just assumed it may be additional effort on xcinfo's end to allow omitting that, so it might not pay off.

note: #27 might be interesting to come before this feature

thanks!

**Comment by trispo** [comment]
Hi @gobetti!

Thanks for your feature request. That's something among what I was implementing during my async/await refactoring over the last days. You can have a look at the async branch. It is not yet ready to be released but it would be great if you could test it beforehand.

regards

**Comment by gobetti** [comment]
thank you @trispo ! I see now after running `xcinfo help install` that  `--disable-xip-deletion` is actually already an option, but apparently `--xip-path` was only added in that async branch you've mentioned (https://github.com/xcodereleases/xcinfo/commit/103e5b0d28036089c7a4450040c8671526aa8999)

just curious, is the full async/await refactor needed to release that piece?

btw, when compiling from the async branch, I didn't see `xip-path` among the options when I ran `xcinfo help` and `xcinfo help install`, where should I see it? thanks!

**Comment by trispo** [comment]
@gobetti I'm planning to release the new async branch soon. Unfortunately I do not have the time to add the changes to the main branch.

Did you ran the compiled version from `.build/debug/xcinfo`? The output should look like this:

![CleanShot 2022-05-04 at 08 07 31](https://user-images.githubusercontent.com/1045441/166631112-a8065a53-28f8-441b-aac4-4a977c4d9f59.png)

**Comment by gobetti** [comment]
shame on me, it turns out I was actually building from the master branch 🤦 thank you, this feature request is already implemented, closing this! 🙌
