### ISSUE TITLE
xcinfo install from local path 

### ISSUE THREAD

**Issue by SVMichael** [xcodereleases/xcinfo#32]
--path /path/to/xcode.xip

**Comment by gobetti** [comment]
see #28

**Comment by trispo** [comment]
Hi @gobetti,
I had very little time he last few month. There's only one minor issue I want to address before releasing the new version. I hope that I can work on it this evening.

**Comment by gobetti** [comment]
@trispo the async branch addresses all my needs and has been working great for me 😊 thank you for all of this!

**Comment by trispo** [comment]
xcinfo 1.0.3 is now available.

**Comment by SVMichael** [comment]
hi @trispo thanks for the update. I do have question, like when using `--xip-path`, it's still asking for the `xcode-version`, I'm thinking if would it be better, if the `xcode-version` argument is optional if the `xip-path` is specified? thanks

**Comment by trispo** [comment]
Hi @gobetti. The version is needed to correctly name the version in the install folder. Otherwise it would be simply called `Xcode.app` which is probably conflicting with an existing version. Any ideas?
