### ISSUE TITLE
duly: Library not loaded: Combine

### ISSUE THREAD

**Issue by BeauNouvelle** [xcodereleases/xcinfo#4]
Running into this issue after following the setup steps as described in the Readme.

```
xcinfo

dyld: Library not loaded: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
  Referenced from: /usr/local/bin/xcinfo
  Reason: image not found
Abort trap: 6

```

EDIT: I'm wondering if this has something to do with me trying to run this on Mojave..

**Comment by ricobeck** [comment]
We're using Combine so you need to have Catalina. 

We could probably replace it with RxSwift but it was intended as our Combine live learning example. :)

**Comment by BeauNouvelle** [comment]
No problem at all. Makes sense to me. I've created a PR to add this to the readme.
https://github.com/xcodereleases/xcinfo/pull/5
