### ISSUE TITLE
Fatal error: Unreachable: file XCModel/Release.swift, line 41

### ISSUE THREAD

**Issue by arrizer** [xcodereleases/xcinfo#7]
Hey there. First of all, I really like the xcinfo tool. I use it to manage my Xcode installations at work and so far it did work just fine. Unfortunately lately I get the following output when running the tool (no matter which sub-command):

Fatal error: Unreachable: file XCModel/Release.swift, line 41

And the process terminates with SIGKILL.
As far as I can tell the fatalError is triggered here: https://github.com/xcodereleases/data/blob/master/Sources/XCModel/Release.swift#L41

I already tried to re-compile the latest version and delete all cache files but the issue persists. Any idea how to resolve that?

**Comment by trispo** [comment]
Hi @arrizer. I've already fixed this issue locally but to push it here I need to wait until https://github.com/xcodereleases/data/pull/8 gets merged. I contacted @xcodereleases yesterday and they promised to have a look it it soon. Please stay tuned.

**Comment by trispo** [comment]
Hi @arrizer,

the issue has been fixed.

**Comment by arrizer** [comment]
@trispo Great! Now it works again. Thank you!
