### ISSUE TITLE
Is it possible to support an installation method like brew install?

### ISSUE THREAD

**Issue by fhefh2015** [xcodereleases/xcinfo#9]
example:
`brew install xcinfo`

**Comment by trispo** [comment]
Yes, this would be nice. Can you create a Pull Request for this?

**Comment by bboles** [comment]
Looks it is done now:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/xcinfo.rb

**Comment by trispo** [comment]
Yes, I did add a PR last week and it got accepted today.

**Comment by trispo** [comment]
I just updated the Readme.
